services:
  api:
    build:
      context: ../..
      dockerfile: code/deployment/api/Dockerfile
    container_name: minimal-api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/../models
    restart: unless-stopped

  app:
    build:
      context: ../..
      dockerfile: code/deployment/app/Dockerfile
    container_name: minimal-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: unless-stopped
